version: '2.1'

services:

  redis:
    image: redis:3.2
    container_name: remotopia-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

  postgres:
   image: postgres:9.6
   container_name: remotopia-postgres
   hostname: postgres
   ports:
     - "5432:5432"
   volumes:
     - "./data/postgres:/var/lib/postgresql/data"
   environment:
     POSTGRES_PASSWORD: postgres
