#!/usr/bin/env bash
#
# Assumes Ubuntu 14.04.

set -e

echo "############################################################"
echo "#                                                          #"
echo "# Installing Redis                                         #"
echo "#                                                          #"
echo "############################################################"
echo
echo
sudo apt-get install -qq redis-server
sudo mkdir -p /etc/redis/conf.d
cat << EOF | sudo tee /etc/redis/conf.d/journaling.conf
appendonly yes
appendfsync everysec
EOF
sudo service redis-server restart

echo "############################################################"
echo "#                                                          #"
echo "# Installing Postgres                                      #"
echo "#                                                          #"
echo "############################################################"
echo
echo
# Add PostgreSQL GPG public key
# to get latest stable
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

# Add PostgreSQL Apt repository
# to get latest stable
sudo touch /etc/apt/sources.list.d/pgdg.list
sudo echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

# Update Apt repos
sudo apt-get update

# Install PostgreSQL
# -qq implies -y --force-yes
sudo apt-get install -qq postgresql postgresql-contrib

# Create new superuser "vagrant"
sudo -u postgres createuser -s vagrant

# Create new user "root" w/ defined password
# Not a superuser, just tied to new db "vagrant"
sudo -u postgres psql -c "CREATE DATABASE vagrant;"
sudo -u postgres psql -c "CREATE ROLE vagrant_root LOGIN PASSWORD 'vagrant' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE vagrant TO vagrant_root;"
sudo -u postgres psql -c "ALTER ROLE vagrant_root superuser;"

# Make sure changes are reflected by restarting
sudo service postgresql restart

echo "############################################################"
echo "#                                                          #"
echo "# Installing Node                                          #"
echo "#                                                          #"
echo "############################################################"
echo
echo
if which curl > /dev/null
    then
        sudo apt-get -y install curl
    else
        echo "curl is installed, skipping..."
    fi

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get -y install nodejs
sudo ln -s /usr/bin/nodejs /usr/bin/node

if which npm > /dev/null
    then
        sudo apt-get -y install npm
    else
        echo "npm is installed, skipping..."
    fi